server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql:///testbank
    username: root
    password: rootpwd
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.mysqldemo.domain